
name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Cache Conan Packages
      - name: Cache Conan Packages
        uses: actions/cache@v3
        with:
          path: ~/.conan/data
          key: ${{ runner.os }}-conan-${{ hashFiles('challengeLC/process_manager/conanfile.txt') }}
          restore-keys: |
            ${{ runner.os }}-conan-

      # 3. Install Conan
      - name: Install Conan
        run: |
          pip install conan

      # 4. Create Conan Default Profile if needed
      - name: Create Conan Default Profile
        run: |
          conan profile detect --force

      # 5. Install spdlog from Source
      - name: Install spdlog
        run: |
          sudo apt update
          sudo apt install -y cmake gcc g++ git
          
          # Clone and build spdlog
          git clone --recursive https://github.com/gabime/spdlog.git
          cd spdlog
          mkdir -p build
          cd build
          cmake ..
          sudo make install
          cd ../../

      # 6. Install Dependencies with Conan
      - name: Install Dependencies with Conan
        run: |
          mkdir -p build
          cd build
          conan install ../process_manager --build=missing

      # 7. Cache CMake Build Directory
      - name: Cache CMake Build Directory
        uses: actions/cache@v3
        with:
          path: build/
          key: ${{ runner.os }}-cmake-${{ hashFiles('challengeLC/process_manager/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-

      # 8. Build Project
      - name: Build Project
        run: |
          cd build
          cmake ../process_manager -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      # 9. Upload Build Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build/
