
name: "Style check"
description: "Style check using clang-format"

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

runs:
  using: "composite"
  steps:
    - name: "Run clang-format"
      shell: bash
      run: |
        # We only make check, not changes
        # Use the find command with the correct paths
        PROJECT_PATH=$(pwd)

        # Specify the correct paths for src and include
        SOURCE_FILES=$(find $PROJECT_PATH/process_manager/src -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
        SOURCE_FILES+=$(find $PROJECT_PATH/process_manager/include -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")

        ERROR_FILE_FLAG=$PROJECT_PATH/clang-format_errors.txt

        echo "Running: clang-format -n $SOURCE_FILES"

        # Run clang-format check
        clang-format -n $SOURCE_FILES 2> ${ERROR_FILE_FLAG}
        
        # Check for errors
        if [ -s $ERROR_FILE_FLAG ]; then
            echo "Error: Some files are not formatted correctly"
            cat $ERROR_FILE_FLAG
            exit 1
        else
            echo "All files are formatted correctly. Niiiceee"
            exit 0
        fi
