
name: Code Formatting with Clang-Format

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install clang-format
      - name: Install Clang-Format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      # Step 3: Run clang-format to check and apply formatting
      - name: Run Clang-Format
        run: |
          # Apply clang-format to the codebase
          clang-format -i process_manager/**/*.cpp process_manager/**/*.h

      # Step 4: Check if clang-format applied any changes
      - name: Check for Formatting Changes
        id: changes
        run: |
          git diff --exit-code || echo "There are formatting changes"
          echo "changes=$(git diff --exit-code)" >> $GITHUB_ENV

      # Step 5: Commit and Push Changes if any formatting was done
      - name: Commit and Push Changes (if any)
        if: env.changes != '0'  # Check if there were changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Apply clang-format"
          git push
