
name: Testing and Code Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Download Build Artifact from the build job
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: process_manager/build/

      # 3. Run Tests
      - name: Run Tests
        run: |
          cd process_manager/build
          ctest --output-on-failure

      # 4. Install gcovr for Coverage Reporting
      - name: Install gcovr
        run: |
          sudo apt-get update
          sudo apt-get install -y gcovr

      # 5. Generate Code Coverage Report
      - name: Generate Code Coverage Report
        run: |
          cd process_manager/build
          gcovr -r ../process_manager --xml-pretty -o coverage.xml
          gcovr -r ../process_manager --html-details -o coverage.html

      # 6. Upload Coverage Reports as Artifacts
      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v3
        with:
          name: CoverageReports
          path: |
            process_manager/build/coverage.xml
            process_manager/build/coverage.html
